stages:
  - build
  - test
  - qa
  - deploy

empaquetar:
  stage: build
  script:
    - mvn package -DskipTests=true
  artifacts:
    paths:
      - target/

pruebas-unitarias:
  stage: build
  script:
    - mvn test

pruebas-funcionales:
  stage: test
  script:
    - echo "pruebas-funcionales"

calidad-codigo:
  stage: qa
  script:
    - echo "calidad-codigo"

despliegue-host-heroku:
  stage: deploy
  script:
    - echo "despliegue-host-heroku"