stages:
  - build
  - test
  - qa
  - deploy

empaquetar:
  stage: build
  script:
    - mvn package -DskipTests=true
  artifacts:
    paths:
      - target/

pruebas-unitarias:
  stage: build
  script:
    - mvn test

pruebas-funcionales:
  stage: test
  dependencies:
    - empaquetar
  script:
    - cp -r target/Baloncesto /usr/local/tomcat/webapps
    - mysql -u root < db/baloncesto.sql
    - export DATABASE_HOST="jdbc:mysql://localhost"
    - export DATABASE_PORT="3306"
    - export DATABASE_NAME="baloncesto"
    - export DATABASE_USER="usuario"
    - export DATABASE_PASS="clave"
    - sh /usr/local/tomcat/bin/catalina.sh stop
    - sh /usr/local/tomcat/bin/catalina.sh start
    - mvn failsafe:integration-test failsafe:verify

calidad-codigo:
  stage: qa
  script:
    - echo "calidad-codigo"

despliegue-host-heroku:
  stage: deploy
  script:
    - echo "despliegue-host-heroku"